setup:
	cd backend && go mod download
	cd frontend && npm install

run-backend:
	cd backend && go run main.go

run-frontend:
	cd frontend && npm run dev

build-frontend:
	cd frontend && npm run build
